const UserActionTypes = {
    FETCH_USERS: 'FETCH_USERS',
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    CHANGE_LIKE_STATUS: 'CHANGE_LIKE_STATUS',
    DELETE_USER: 'DELETE_USER'
}

export default UserActionTypes;
